name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Set up test environment variables
      run: |
        echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_db" >> $GITHUB_ENV
        echo "REDIS_URL=redis://localhost:6379" >> $GITHUB_ENV
        echo "TESTING=true" >> $GITHUB_ENV

    - name: Run tests with coverage
      run: |
        cd backend
        python -m pytest

    # - name: Upload coverage reports to Codecov
    #   if: success()
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./backend/coverage.xml
    #     directory: ./backend
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: false

    - name: Upload coverage to GitHub
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: backend/htmlcov/ 